### ISSUE TITLE
I think this is a Good Project

### ISSUE THREAD

**Issue by StarryCamile** [Halqq/misericordia-client#1]
I am engaged in Minecraft Hack client development, can I join? I have my own discord, but I am a Chinese person

**Comment by Halqq** [comment]
> I am engaged in Minecraft Hack client development, can I join? I have my own discord, but I am a Chinese person

you can give me ideas and make constructive criticism, call me on discord: halq#7958

**Comment by StarryCamile** [comment]
ok i sent
